-- Generated from the Portuguese product pages. Safe to run repeatedly.
insert into public.products (sku, slug, name) values
  ('009', 'armacao-artistica', 'Armação Artística'),
  ('0023', 'armacao-slim-preta', 'Armação Slim Preta'),
  ('007', 'aviador-classico', 'Aviador Clássico'),
  ('0333', 'aviador-elegante', 'Aviador Elegante'),
  ('0014', 'aviador-escuro', 'Aviador Escuro'),
  ('0158', 'aviador-paris', 'Aviador Paris'),
  ('0137', 'aviadores-dourados', 'Aviadores Dourados'),
  ('0045', 'aviadores-prateados', 'Aviadores Prateados'),
  ('0776', 'cartao-presente', 'Cartão-Presente'),
  ('001', 'cottet-barcelona', 'Cottet Barcelona'),
  ('0099', 'cottet-paris', 'Cottet Paris'),
  ('0543', 'estojo-em-pele', 'Estojo em Pele'),
  ('0133', 'lennons-metalicos', 'Lennons Metálicos'),
  ('0056', 'lennons-prateados', 'Lennons Prateados'),
  ('0022', 'lennons-transparentes', 'Lennons Transparentes'),
  ('0046', 'lennons-verdes', 'Lennons Verdes'),
  ('0088', 'meteor-wild', 'Meteor Wild'),
  ('0040', 'modelo-exclusivo-2', 'Óculos de Sol Homem'),
  ('0037-1', 'modelo-exclusivo', 'Modelo Exclusivo'),
  ('0015', 'oculos-brilhantes', 'Óculos Brilhantes'),
  ('0134', 'oculos-cat-eye', 'Óculos Cat-Eye'),
  ('0010', 'oculos-de-sol-circulares', 'Óculos de Sol Circulares'),
  ('00312', 'oculos-de-sol-meteor', 'Óculos de Sol Meteor'),
  ('0037', 'oculos-de-sol-mulher', 'Óculos de Sol Mulher'),
  ('0306', 'oculos-de-sol-retro', 'Óculos de Sol Retro'),
  ('0043', 'oculos-de-sol-slim', 'Óculos de Sol Slim'),
  ('0042', 'oculos-de-sol-verao', 'Óculos de Sol Verão'),
  ('005', 'oculos-dourados', 'Óculos Dourados'),
  ('0017', 'oculos-escuros', 'Óculos Escuros'),
  ('0222', 'oculos-fashion', 'Óculos Fashion'),
  ('0100', 'oculos-graduados', 'Óculos graduados'),
  ('003', 'oculos-marshal', 'Óculos Marshal'),
  ('004', 'oculos-redondos-wild', 'Óculos Redondos Wild'),
  ('008', 'oculos-redondos', 'Óculos Redondos'),
  ('0541', 'oculos-rosa', 'Óculos Rosa'),
  ('0037-1-1', 'oculos-royal', 'Óculos Royal'),
  ('002', 'oculos-slim', 'Óculos Slim'),
  ('0078', 'oculos-sol-filtro-suave', 'Óculos de Sol Filtro Suave'),
  ('006', 'oculos-transparentes', 'Óculos Transparentes'),
  ('0053', 'oculos-trendy', 'Óculos Trendy'),
  ('0422', 'oculos-verao-2', 'Óculos Art'),
  ('0358', 'oculos-verao', 'Pilot Escuro'),
  ('0138', 'oculos-vintage', 'Óculos Vintage'),
  ('0012', 'oculos-way', 'Óculos Way'),
  ('0136', 'oculos-wild', 'Óculos Wild'),
  ('0018', 'otica-escura', 'Ótica escura'),
  ('0567', 'pack-duo', 'Pack Duo'),
  ('0453', 'padrao-animal', 'Padrão Animal'),
  ('0011', 'pilot-dourado', 'Pilot Dourado'),
  ('0019', 'pilot-verde', 'Pilot Verde'),
  ('0135', 'produto-3', 'Óculos de Autor'),
  ('0016', 'redondos-classicos', 'Redondos Clássicos'),
  ('0054', 'thalia-preto', 'Thalia Preto'),
  ('0013', 'thalia-redondos', 'Thalia Redondos'),
  ('0706', 'vale', 'Vale')
on conflict (slug) do update set
  sku = coalesce(excluded.sku, public.products.sku),
  name = excluded.name,
  updated_at = now();
